version: '3.8'

services:
  app:
    build: .
    ports:
      - "3067:3067"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/foodOrderDB
    volumes:
      - .:/usr/src/app

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

