apiVersion: v1
kind: Service
metadata:
  name: foodmenu
spec:
  selector:
    app: foodmenu
  ports:
    - protocol: TCP
      port: 80          # Exposing port 80 externally
      targetPort: 3067   # Targeting the container's internal port 3067
  type: LoadBalancer
